---

- name: check for required variables
  ansible.builtin.assert:
    that:
      - env_files_path
      - github_username
      - git_name
      - git_email

- name: dotfiles folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.dotfiles"
    state: directory
    mode: 0755

- name: copy dotfiles
  ansible.builtin.copy:
    src: files/.dotfiles
    dest: "{{ ansible_user_dir }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0655

- name: Create symbolic link for .direnvrc
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.dotfiles/.direnvrc"
    dest: "{{ ansible_user_dir }}/.direnvrc"
    force: true
    state: link

- name: vimrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.vimrc"
    marker: '" {mark} ANSIBLE MANAGED BLOCK'
    create: true
    mode: 0755
    block: |
      set spell spelllang=en_us
      hi clear SpellBad
      hi SpellBad cterm=underline,bold ctermfg=red
      if has("autocmd")
        au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
      endif
      set number
      set ignorecase
      set smartcase

- name: copy fonts
  ansible.builtin.copy:
    src: files/.fonts
    dest: "{{ ansible_user_dir }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0655"

- name: Create symbolic link for .desk
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.dotfiles/.desk"
    dest: "{{ ansible_user_dir }}/.desk"
    force: true
    state: link

- name: copy env-files.d files
  become: false
  ansible.builtin.copy:
    src: files/.env-files.d/
    dest: "{{ env_files_path }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0660

- name: create cookiecutter env file
  ansible.builtin.copy:
    dest: "{{ env_files_path }}/cookie-cutter"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0660
    content: export COOKIECUTTER_CONFIG={{ ansible_user_dir }}/.dotfiles/cookie-cutter.yml

- name: create cookiecutter default file
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.dotfiles/cookie-cutter.yml"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0660
    content: |
      ---

      default_context:
        full_name: "{{ git_name }}"
        email: "{{ git_email }}"
        github_username: "{{ github_username }}"
