---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  vars:
    env_files_path: /tmp
    github_username: myusername
    git_name: Some User
    git_email: nobody@example.com
  tasks:
    - name: Verify env dir
      block:
        - name: Stat env-files dir
          ansible.builtin.stat:
            path: "{{ env_files_path }}"
          register: env_files_path
        - name: Env_files_path isdir
          ansible.builtin.assert:
            that: env_files_path.stat.isdir

    - name: Verify fonts dir
      block:
        - name: Stat fonts dir
          ansible.builtin.stat:
            path: "{{ ansible_user_dir }}/.fonts"
          register: fonts_dir
        - name: Fonts_dir isdir
          ansible.builtin.assert:
            that: fonts_dir.stat.isdir
